/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** チケット一覧（フィルタ / ソート / ページング） */
        get: operations["listTickets"];
        put?: never;
        /** チケット作成 */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** チケット詳細 */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        /** チケット削除 */
        delete: operations["deleteTicket"];
        options?: never;
        head?: never;
        /** チケット更新 */
        patch: operations["updateTicket"];
        trace?: never;
    };
    "/api/tickets/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** コメント一覧 */
        get: operations["listComments"];
        put?: never;
        /** コメント作成 */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 集計（ステータス別 / 担当者別 / 月次作成数） */
        get: operations["getAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        TicketStatus: "TODO" | "IN_PROGRESS" | "REVIEW" | "DONE";
        /** @enum {string} */
        TicketPriority: "LOW" | "MEDIUM" | "HIGH";
        Ticket: {
            id: string;
            title: string;
            description: string;
            status: components["schemas"]["TicketStatus"];
            priority: components["schemas"]["TicketPriority"];
            assigneeId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateTicketInput: {
            title: string;
            description: string;
            status?: components["schemas"]["TicketStatus"];
            priority: components["schemas"]["TicketPriority"];
            assigneeId: string;
        };
        UpdateTicketInput: {
            title?: string;
            description?: string;
            status?: components["schemas"]["TicketStatus"];
            priority?: components["schemas"]["TicketPriority"];
            assigneeId?: string;
        };
        TicketListResponse: {
            data: components["schemas"]["Ticket"][];
            total: number;
            page: number;
            pageSize: number;
        };
        User: {
            id: string;
            name: string;
        };
        Comment: {
            id: string;
            ticketId: string;
            authorId: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateCommentInput: {
            authorId: string;
            content: string;
        };
        Analytics: {
            byStatus: {
                status: components["schemas"]["TicketStatus"];
                count: number;
            }[];
            byAssignee: {
                assigneeId: string;
                count: number;
            }[];
            monthlyCreated: {
                /** @description YYYY-MM */
                month: string;
                count: number;
            }[];
        };
        Error: {
            message: string;
            code?: string;
        };
    };
    responses: {
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTickets: {
        parameters: {
            query?: {
                status?: components["schemas"]["TicketStatus"];
                priority?: components["schemas"]["TicketPriority"];
                assigneeId?: string;
                /** @description タイトル部分一致 */
                search?: string;
                sort?: "createdAt" | "updatedAt" | "priority" | "status";
                order?: "asc" | "desc";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketListResponse"];
                };
            };
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTicketInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTicketInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
        };
    };
    getAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analytics"];
                };
            };
        };
    };
}
